FROM node:14-alpine
WORKDIR /usr/src/app

COPY ./microservices/stats/package*.json ./
RUN npm install --silent

COPY ./microservices/stats ./

RUN npm run build

EXPOSE 3002

CMD [ "npm", "run", "start:prod" ]
