FROM node:14-alpine
WORKDIR /usr/src/app

COPY ./microservices/user/package*.json ./
RUN npm install --silent

COPY ./microservices/user ./

RUN npm run build

EXPOSE 3001

CMD [ "npm", "run", "start:prod" ]
