FROM node:14-alpine
WORKDIR /usr/src/app

COPY ./microservices/firebase/package*.json ./
RUN npm install --silent

COPY ./microservices/firebase ./

RUN npm run build

EXPOSE 3006

CMD [ "npm", "run", "start:prod" ]
