FROM node:14-alpine
WORKDIR /usr/src/app

COPY ./microservices/api/package*.json ./
RUN npm install --silent

COPY ./microservices/api ./

RUN npm run build

EXPOSE 3007

CMD [ "npm", "run", "start:prod" ]
